### ISSUE TITLE
Failure detecting non-compliant USB flash

### ISSUE THREAD

**Issue by ghost** [linuxmint/mintstick#20]
MintStick fails to detect Sandisk SDCZ80-032G "32gb Extreme USB 3.0", and probably many others.

In order to appear in the Windows XP bootloader, firmware erroneously reports DRIVE_FIXED instead of DRIVE_REMOVABLE per-
http://www.911cd.net/forums//index.php?s=38512613c2dfc5180aeaf70ed423a764&showtopic=19768&st=0&p=132085&#entry132085

udisks --dump, reports "Removable: 0", which mintstick.py (in Git) queries beginning on line 196, specifically on line 207 "and (str(dev.Get('', 'DeviceIsRemovable')) == "1") \".

The fault is the manufacturer's, and mintstick's behaviour is technically correct, but it makes life difficult for novice users with random USB sticks, and forum & IRC helpers.

"rufus" USB image writer for Windows has an Alt-F mode to enable fixed-disk detection, which works for this stick, per-
https://github.com/pbatard/rufus/issues/134

A command-line switch ("mintstick --fixed" etc) could easily handle these drives without pestering users.

**Comment by xenopeek** [comment]
Thanks for contributing to mintstick. Considering there have been no updates to this issue since mid 2014 and mintstick switched to udisks2 two years ago, which may have solved the issue if it was still affecting users back then, I'm closing it for now.

If the issue happens again, please test against the latest mintstick version, go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be mintstick.
