### ISSUE TITLE
unable to detect my flash drive

### ISSUE THREAD

**Issue by philipzae** [linuxmint/mintstick#21]
I'm running mintstick 1.1.9 on lmde and my SanDisk Corp. Cruzer Blade 32gb flash drive is not detected by the utility. usb-creator-gtk on linux mint 13 is able to detect it correctly.

After using mintstick to write lmde's iso to a 4gb flash drive, lmde is unable to mount the created partition and when i load gparted it states "invalid partition table - recursive partition on /dev/sdb." linux mint 13 is able to mount the partition even though gparted gives the same error.

**Comment by ffopbr** [comment]
I am having this problem too.

**Comment by xenopeek** [comment]
Thanks for contributing to mintstick. Considering there have been no updates to this issue since mid 2015 and mintstick switched to udisks2 two years ago, which may have solved the issue if it was still affecting users back then, I'm closing it.

If the issue happens again, please test against the latest mintstick version, go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be mintstick.
