### ISSUE TITLE
error in manjaro

### ISSUE THREAD

**Issue by poltiser** [linuxmint/mintstick#22]
after install - USB Stick Formatter did not work - I run it in terminal with error:

mintstick -m format
  File "/usr/lib/mintstick/raw_format.py", line 41
    print "Geometry error - Can't create partition"
                                                  ^
SyntaxError: invalid syntax

Pls advise...

**Comment by who-me** [comment]
This is probably fixed now due to /usr/bin/python2 being called explicitly instead of  /usr/bin/python which on newer distros can point to python 3.
 
I suggest you install mintstick-git from the AUR. It's already there on the new AUR:
https://aur4.archlinux.org/packages/mintstick-git
 
Not sure how the transition from the old version to the new one is being handled.

**Comment by xenopeek** [comment]
Thanks for contributing to mintstick. Considering there have been no updates to this issue since mid 2015 and it appears solved from silviucc's comment I'm closing it.

If the issue happens again, please test against the latest mintstick version, go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be mintstick.
