### ISSUE TITLE
MintStick as USB Image Writer completely broken in Linux Mint 16 KDE and Linux Mint 17 KDE

### ISSUE THREAD

**Issue by mauromol** [linuxmint/mintstick#32]
Please see this Launchpad bug:
https://bugs.launchpad.net/linuxmint/+bug/1313295

**Comment by xenopeek** [comment]
Thanks for contributing to mintstick. Considering there have been no updates to this issue since late 2014 I assume it's no longer affecting users so I'll close it.

If the issue happens again, please test against the latest mintstick version, go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be mintstick.

**Comment by mauromol** [comment]
Sorry, I don't want to be sharp, but by virtue of this issue not being updated since late 2014, people simply stopped to use mintstick. At least this is my case.
