### ISSUE TITLE
mintstick destroy confirmation translated but not appears on the UI

### ISSUE THREAD

**Issue by KAMI911** [linuxmint/mintstick#33]
I translated this string:
https://translations.launchpad.net/linuxmint/latest/+pots/mintstick/hu/+translate?batch=10&show=all&search=will

but the confirmation window still shows the English string. Linux Mint/32bit/Cinnamon/Hungarian

Also reported here: https://bugs.launchpad.net/linuxmint/+bug/1390854

**Comment by monsta** [comment]
That page still shows the translation made on 2013-12-12, and it's in [mint-translations package](https://github.com/linuxmint/mint-translations/blob/master/po-export/mintstick/mintstick-hu.po#L100) as well. Is that alright?

**Comment by NikoKrause** [comment]
@KAMI911 Can you make a screenshot of your issue?

**Comment by xenopeek** [comment]
Thanks for contributing to mintstick. Considering there have been no updates from the author since late 2014 I assume it's no longer affecting users so I'll close it.

If similar issues still occur please refer to our [translation guide](https://linuxmint-translation-guide.readthedocs.io/en/latest/)) to improve translations for mintstick.
