### ISSUE TITLE
Attempt to write image from smb share (mounted via gvfs) fails with unknown error

### ISSUE THREAD

**Issue by qgates** [linuxmint/mintstick#41]
*\* Affects Mint 17.1 / 17.2, 32/64 bit, Cinnamon and Mate editions

Steps to reproduce (Cinnamon 17.2):
1. Using Nemo (file browser) browse Network in left hand pane to connect to an smb share containing an ISO to write. Share is automounted into mountpoint /run/user/xxxx/gvfs/smb-share:xxxx
2. Launch USB Image Writer
3. Select Image to write, browse to /run/user/xxxx/gvfs/smb-share:xxxx
4. Select ISO file from the file browser.
5. Select an inserted USB stick to write to.
6. Click "Write". Image Writer asks for password.
7. Immediately, an error box appears "An Error Occurred". Nothing is written to the USB stick.

Workaround: Instead of browsing with nemo to mount the network share, manually mounting into a local folder with:
`$ sudo mount -t cifs //1.2.3.4/sharename ~/mymountpoint -o username=myuser`

... and selecting the ISO by browsing to ~/mymountpoint works just fine.

I can't figure why this is failing. Everything under /run/user/xxxx has current user/group ownership and read/write permissions. I can only assume that the parent dir ownerships of "root:root" for /run and /run/user might be tripping mintstick up here. Interestingly, using the "sudo mount" approach above, mountpoint permissions are "root:users", but permissions are 777. Perhaps that's enough for mintstick to work.

**Comment by xenopeek** [comment]
Thanks for contributing to mintstick. Considering there have been no updates to this issue since mid 2015 and mintstick switched to udisks2 two years ago, which may have solved the issue if it was still affecting users back then, I'm closing it.

If the issue happens again, please test against the latest mintstick version, go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be mintstick.
