### ISSUE TITLE
Unable to detect /dev/mmcblk0 as a flash drive

### ISSUE THREAD

**Issue by show0k** [linuxmint/mintstick#45]
Every SD cards inserted on my embedded SD card reader of my laptop are mounted to /dev/mmcblk0 which is not detcted.

**Comment by xenopeek** [comment]
Thanks for contributing to mintstick. mintstick is an USB thumb drive ISO image writer so supporting SD cards would be a feature request I think. Considering there have been no updates to this issue since early 2016 and mintstick switched to udisks2 shortly after, which may have changed how mintstick recognizes removable storage, I'll close it for now.

If this feature request is still current, please test against the latest mintstick version, go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue with a feature request if the responsible component proves to be mintstick.
