### ISSUE TITLE
version not visible

### ISSUE THREAD

**Issue by Trombonista** [linuxmint/mintstick#85]
mintstick seems not to show a version, neither in GUI nor when called from shell, even with option --debug. Usual option "--version" is not recognized.
I have seen that in Mint 20.1 cinnamon-edge.

**Comment by xenopeek** [comment]
You can use `apt version mintstick` to show the version.

A change to add the --version flag was rejected previously. It was rejected because it hardcoded the version in the code, or invoked dpkg from the program (not cross-distro) to get the version. If any wants to implement this do it in a way that other Linux Mint programs written in Python do, with a Debian rule. See __DEB_VERSION__ in mintupdate https://github.com/linuxmint/mintupdate/search?q=__DEB_VERSION__&type=code or in mintreport https://github.com/linuxmint/mintreport/search?q=__DEB_VERSION__ for examples.
